[package]
name = "lapce-python"
version = "0.3.2"
edition = "2021"

[dependencies]
anyhow = "1.0"
flate2 = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lapce-plugin = { git = "https://github.com/lapce/lapce-plugin-rust.git", branch = "master" }
