name = "lapce-python"
version = "0.3.2"
author = "various"
display-name = "Python (python-lsp-server)"
description = "Python for Lapce using python-lsp-server"
wasm = "lapce-python.wasm"
icon = "python-logo-only.png"

[activation]
language = ["python"]

[config."volt.serverPath"]
default = ""
description = "Path to pylsp bin e.g. /home/me/project/venv/bin/pylsp"

[config."volt.serverArgs"]
default = []
description = "Arguments to pass to the LSP server during launch"
